#!/usr/bin/env python3
"""Convert a BibTeX file to a simple YAML list for Jekyll `_data/publications.yml`.

Usage: python3 scripts/bib_to_yaml.py input.bib output.yml

This script uses `bibtexparser`. If it's missing the script will try to install it.
"""
import sys
import subprocess
from pathlib import Path

def ensure_bibtexparser():
    try:
        import bibtexparser  # type: ignore
    except Exception:
        print('bibtexparser not found, installing...')
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'bibtexparser'])

def parse_bib(input_path):
    import bibtexparser
    with open(input_path, encoding='utf-8') as fh:
        bib_database = bibtexparser.load(fh)
    return bib_database.entries

def entry_to_dict(e):
    # Normalize common fields
    d = {}
    d['id'] = e.get('ID')
    d['title'] = e.get('title', '').replace('{', '').replace('}', '')
    d['authors'] = e.get('author', '')
    d['year'] = int(e['year']) if 'year' in e and e['year'].isdigit() else e.get('year')
    d['venue'] = e.get('journal') or e.get('booktitle') or e.get('publisher') or ''
    d['url'] = e.get('url') or e.get('doi') or ''
    return d

def to_yaml(entries, out_path):
    import yaml
    # Convert entries
    list_entries = [entry_to_dict(e) for e in entries]
    # Write YAML
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('# Generated by scripts/bib_to_yaml.py\n')
        yaml.safe_dump(list_entries, fh, sort_keys=False, allow_unicode=True)

def main():
    if len(sys.argv) < 3:
        print('Usage: bib_to_yaml.py input.bib output.yml')
        sys.exit(2)
    inp = Path(sys.argv[1])
    out = Path(sys.argv[2])
    if not inp.exists():
        print('Input file not found:', inp)
        sys.exit(2)
    ensure_bibtexparser()
    entries = parse_bib(inp)
    # Ensure PyYAML is available
    try:
        import yaml  # type: ignore
    except Exception:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'pyyaml'])
    to_yaml(entries, out)
    print('Wrote', out)

if __name__ == '__main__':
    main()
